---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/wksctl version
    register: wksctl_test_output
  - name: wksctl version
    debug:
      msg: '{{ wksctl_test_output.stdout }}'
