---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install
  become: yes
  stat:
    path: '{{ wksctl_install_dir }}'
  changed_when: False
  register: wksctl_binary
- when: not wksctl_binary.stat.exists
  block:
    - name: download
      become: yes
      become_user: root
      get_url:
        url: '{{ wksctl_url }}'
        dest: /tmp/{{ wksctl_tgz }}
        mode: 0644
        checksum: '{{ wksctl_checksum }}'
    - name: mkdir
      become: yes
      become_user: root
      file:
        path: '{{ wksctl_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{ wksctl_tgz }}
        dest: '{{ wksctl_install_dir }}'
        creates: '{{ wksctl_fq_exe }}'
  always:
    - name: cleanup
      become: yes
      become_user: root
      file:
        path: /tmp/{{ wksctl_tgz }}
        state: absent
- name: link
  become: yes
  become_user: root
  file:
    src: '{{ wksctl_fq_exe }}'
    dest: '{{ wksctl_link }}'
    state: link
