---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: checking for install in {{ wksctl_install_dir }}
  become: true
  stat:
    path: '{{ wksctl_install_dir }}'
  changed_when: False
  register: wksctl_binary
- when: not wksctl_binary.stat.exists
  block:
    - name: downloading {{ wksctl_url }}
      become: true
      become_user: root
      get_url:
        url: '{{ wksctl_url }}'
        dest: '{{ wksctl_tmp_tgz }}'
        mode: 0644
        checksum: '{{ wksctl_checksum }}'
    - name: mkdir {{ wksctl_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ wksctl_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchiving {{ wksctl_tmp_tgz }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ wksctl_tmp_tgz }}'
        dest: '{{ wksctl_install_dir }}'
        creates: '{{ wksctl_exe }}'
  always:
    - name: rm {{ wksctl_tmp_tgz }}
      become: true
      become_user: root
      file:
        path: '{{ wksctl_tmp_tgz }}'
        state: absent
- name: linking {{ wksctl_link }} to {{ wksctl_exe }}
  become: true
  become_user: root
  file:
    src: '{{ wksctl_exe }}'
    dest: '{{ wksctl_link }}'
    state: link
